# Generated by Django 3.2.6 on 2021-09-26 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rwanda_treegovmap', '0002_auto_20210926_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_time', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.leader')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.provinces')),
            ],
        ),
    ]
