# Generated by Django 3.2.6 on 2021-09-26 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rwanda_treegovmap', '0004_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='district_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='GalleryImages/')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_time', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.district')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.provinces')),
            ],
        ),
        migrations.CreateModel(
            name='cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_time', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.district')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.leader')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.provinces')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rwanda_treegovmap.sector')),
            ],
        ),
    ]
