# Generated by Django 3.2.6 on 2021-09-30 07:35

from django.db import migrations, models
import rwanda_treegovmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('rwanda_treegovmap', '0006_auto_20210926_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(default='No-img.jpg', upload_to=rwanda_treegovmap.models.nameFile),
        ),
    ]
